version: "3.9"
services:
  micro1:
    build:
      context: ./micro-1/
    environment:
      HOST: "${MICRO1_HOST}"
      PORT: "${MICRO1_PORT}"
    ports:
      - "3001:${MICRO1_PORT}"
  micro2:
    build:
      context: ./micro-2/
    environment:
      HOST: "${MICRO2_HOST}"
      PORT: "${MICRO2_PORT}"
    ports:
      - "3002:${MICRO2_PORT}"
  micro3:
    build:
      context: ./micro-3/
    environment:
      HOST: "${MICRO3_HOST}"
      PORT: "${MICRO3_PORT}"
    ports:
      - "3003:${MICRO3_PORT}"
